### ISSUE TITLE
How to connect between front and backend?

### ISSUE THREAD

**Issue by sooperset** [vbookshelf/Bert-Toxic-Text-Detector#1]
Hi, I'm new on the web service.

I followed GCP and flask&niginx setting.
However, I couldn't know how to show the main page beautifully.
Would you tell me how to connect front and backend?

**Comment by vbookshelf** [comment]
Hi @soomiles. I am also still learning how to do this.

There are two ways to get the frontend website working and looking nice. With the first method you will be able to display the webpage using the same server where you uploaded the backend code. With the second method you will need to upload the frontend files to a web host like Dreamhost or Hostgator.

Before starting make sure to change the endpoint address in the index.html to match the address of your backend server. This is the line that needs to be changed:

`$.post("http://139.59.50.72/predict", JSON.stringify(message), function(response){`


**Method 1**

Place the frontend code in a folder called static. Then upload this folder together with your backend files when you set up your server. Flask will automatically display html files that are in the static folder. You will then be able to access the main page by typing the address like this:

http://139.59.82.197/static/predict.html
http://[your-server-ip]/static/[html-file-with-same-name-as-endpoint].html

This approach is explained in this tutorial:
https://deeplizard.com/learn/video/SI1hVGvbbZ4

Here you will be able to see an example of a backend folder structure that uses a static folder:
https://github.com/vbookshelf/Automated-Wheat-Counter/tree/master/Wheat-Counter-Docker-Flask-App%20

**Method 2**

Set up a web hosting account and buy a cheap domain. Then upload all the files inside the frontend folder to your domain as you would do when uploading a normal website.
Be sure to first change the server ip address in the index.html file to match the server where your backend code is running.

Good luck.

**Comment by sooperset** [comment]
Thank you!
Your project has inspired me a lot :)
